[package]
name = "raymarching"
version = "0.1.0"
authors = ["loovjo <jonathan.loov@gmail.com>"]
edition = "2018"

[dependencies]
ytesrev = "0.2.4"
sdl2 = "*"
rayon = "1.5.1"
packed_simd = { version = "0.3.6", package = "packed_simd_2" }
